### ISSUE TITLE
Maps have visual issues no one cares about

### ISSUE THREAD

**Issue by LeonardoTheMutant** [Jiskster/SRBZ#18]
It is extremely easy to find a visual bug, sprite/texture overdraw or a missing texture in the wall in about every map. I will not go through each of these issues here because they are very noticeable in a regular playthrough.

Most of the issues appear in the Software renderer but there are unique OpenGL issues as well. Just play through these maps in both renderers and you will see them yourself.

*Some of them are extremely easy to fix*

**Comment by Jiskster** [comment]
vague
